services:
  db:
    image: mysql:8.0
    container_name: prode-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password_aca
      MYSQL_DATABASE: prode_db
      MYSQL_USER: prode_usr
      MYSQL_PASSWORD: user_password_aca
    ports:
      - "3306:3306"